import Head from 'next/head';
import Navbar from '../../components/navbar';
import styles from '../../styles/Home.module.css'

export default function MovieItem({ info }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CinemaNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div class="px-2 pt-16">
          <div class="z-20 p-2 pb-4 bg-white rounded-md grid justify-items-center content-center">
            <h1 class="md:text-2xl text-1xl font-bold text-emerald-500">
              {info.title}
            </h1>

            <p class="text-1sm font-bold text-indigo-500">
              Ano: {info.release_date.split('-',1)} | Nota: {info.vote_average}
            </p>

            <p class="text-1sm p-8 font-regular text-black-500">
              {info.overview}
            </p>

            <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="800" class="rounded-md" />
          </div>
        </div>
      </main>


    </div>

  )
}


export async function getServerSideProps(context) {

  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
  const json = await res.json();

  console.log("JSON", json);

  return {
    props: {
      info: json.info
    }
  };
}
