import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/navbar';
import styles from '../styles/Home.module.css'

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CinemaNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


     <Navbar/>

      <main className={styles.main}>
        <div class="px-2 md:pt-16 pt-12">
          <div class="fixed z-20 p-2 mx-2 bg-white rounded-md text-emerald-500">
            <Link href="/busca">Ir para Busca</Link>
            <br></br>
            <Link href="/sobre">Sobre</Link>
          </div>
          <div class="h-full bg-white sm:ml-32 rounded-md">
            <ul class="grid md:grid-cols-4 grid-cols-1 p-2">
              {list.map(item => (
                <li class="grid grid-cols-1 bg-emerald-500 hover:bg-emerald-400 rounded-lg">
                  <a href={`movie/${item.id}`} class="hover:bg-black-700">
                    <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} class="w-full h-60 object-cover rounded-lg"/>
                    <div class="relative p-2 col-start-1 row-start-1 flex flex-col-reverse">
                      <p class="mt-1 text-lg font-semibold text-white">{item.title}</p>
                    </div>
                  </a>
                </li>
              ))}
            </ul>

          </div>
        </div>





      </main>

    </div>
  )
}


export async function getServerSideProps() {

  const res = await fetch('http://localhost:3000/api/trending');
  const json = await res.json();

  return {
    props: {
      list: json.list
    }
  };
}
