import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Navbar from '../components/navbar';
import styles from '../styles/Home.module.css'

export default function About({ author }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CinemaNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div class="px-2 pt-16">
          <div class="z-20 p-2 pb-4 bg-white rounded-md grid justify-items-center content-center">
            <h1 class="md:text-2xl text-1xl font-bold text-emerald-500">
             Sobre o projeto
            </h1>

            <p class="pt-8 text-1sm font-bold text-indigo-500">Criado a partir da video aula: </p>
            <a class="text-1sm font-regular text-black-500" href="https://www.youtube.com/watch?v=xjrDEZQ5LnA"> Primeiros Passos com Next.js - Bonieky Lacerda </a>


            <p class="pt-8 text-1sm font-bold text-indigo-500">Feito por:</p>
            <a class="text-1sm font-regular text-black-500" href="https://ciromoura.com.br"> {author} </a>

           
          </div>
        </div>

      </main>

    </div>
  )
}


export async function getStaticProps() {


  return {
    props: {
      author: "@CiroMoura"
    }
  };
}
